general.import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
padding = { x = 10, y = 10 }
dynamic_padding = true
option_as_alt = "Both"

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Light" }
bold = { family = "FiraCode Nerd Font Mono", style = "Medium" }
size = 16
offset = { x = 0, y = 1 }
