general.import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
padding = { x = 20, y = 20 }

option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Thin" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Medium" }
size = 16
